### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by goldyfruit** [MichaelDurfey/mf-dynamic-remote-component#4]
Hi @MichaelDurfey!

Just a quick thank you, you library made everything easier to me.

Keep up the good work :muscle:

**Comment by MichaelDurfey** [comment]
Thanks @goldyfruit ! Really appreciate the comments

**Comment by goldyfruit** [comment]
> Thanks @goldyfruit ! Really appreciate the comments

You are very welcome! :+1:
