### ISSUE TITLE
Works with "quasar dev" but not with "quasar build" served by Nginx

### ISSUE THREAD

**Issue by goldyfruit** [MichaelDurfey/mf-dynamic-remote-component#5]
Hi @MichaelDurfey,

I'm running more test with your library and just got my first glitch with it.

When running the code via `quasar dev` everything is running fine but when I run `quasar build` and serve the `dist/spa/` vie Nginx I got the error below.

![image](https://github.com/MichaelDurfey/mf-dynamic-remote-component/assets/614115/1becb964-bbb0-4d60-8fdb-706925656d04)

For some reason, the host _(port 3002)_ tries to load a page which does exist only on the remote _(port 3001)_.

- Does not exist http://localhost:3002/js/998.20e2e8f5.js (host)
- Does exist http://localhost:3001/js/998.20e2e8f5.js (remote)

Here is the code from the host:

```javascript
<script setup lang="ts">
import { RemoteComponent } from 'mf-dynamic-remote-component';
import { defineAsyncComponent } from 'vue';

const config = {
  path: 'http://localhost:3001/remoteEntry.js',
  scope: 'app_expose',
  module: './RemoteSkill.vue',
};
const RemoteSkill = defineAsyncComponent(() => RemoteComponent(config));
</script>

<template>
    <component :is="RemoteSkill"></component>
</template>
```

I'm not sure if its an issue with this library or me missing something on the webpack configuration.

**Comment by goldyfruit** [comment]
Still debugging, if I run `quasar build` on host but run `quasar dev` on remote it works, if I run `quasar build` on remote as well I got the situation from above.

**Comment by MichaelDurfey** [comment]
Hi @goldyfruit , this doesn't seem like an issue with this library to me looking at the issue. The path that you're providing doesn't exist. We also get a pretty good error message indicating this.
